name: project

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check formatting with Black
        run: |
          pip install black
          black --check src tests

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src tests

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

  smoke-test-api:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t credit-risk-api .

      - name: Start API container
        run: |
          docker run -d --name api -p 8000:8000 credit-risk-api
          sleep 10

      - name: Smoke test /predict
        run: |
          python - <<'EOF'
import requests, json
FEATURE_ORDER = json.load(open("src/api/feature_order.json"))
dummy = {feat: 0.0 for feat in FEATURE_ORDER}
r = requests.post("http://localhost:8000/predict", json={"features": dummy})
assert r.status_code == 200, r.text
print("OK:", r.json())
EOF

      - name: Tear down
        run: docker rm -f api
